export const data = [
  {
    Title: "The Shawshank Redemption",
    Year: "1994",
    Rated: "R",
    Released: "14 Oct 1994",
    Runtime: "142 min",
    Genre: "Drama",
    Director: "Frank Darabont",
    Writer: "Stephen King, Frank Darabont",
    Actors: "Tim Robbins, Morgan Freeman, Bob Gunton",
    Plot: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 7 Oscars. 21 wins & 43 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.3/10",
      },
      {
        Source: "Metacritic",
        Value: "80/100",
      },
    ],
    Metascore: "80",
    imdbRating: "9.3",
    imdbVotes: "2,434,594",
    imdbID: "tt0111161",
    Type: "movie",
    DVD: "21 Dec 1999",
    BoxOffice: "$28,699,976",
    Production: "Columbia Pictures, Castle Rock Entertainment",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Godfather",
    Year: "1972",
    Rated: "R",
    Released: "24 Mar 1972",
    Runtime: "175 min",
    Genre: "Crime, Drama",
    Director: "Francis Ford Coppola",
    Writer: "Mario Puzo, Francis Ford Coppola",
    Actors: "Marlon Brando, Al Pacino, James Caan",
    Plot: "An organized crime dynasty's aging patriarch transfers control of his clandestine empire to his reluctant son.",
    Language: "English, Italian, Latin",
    Country: "United States",
    Awards: "Won 3 Oscars. 31 wins & 30 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.2/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "97%",
      },
      {
        Source: "Metacritic",
        Value: "100/100",
      },
    ],
    Metascore: "100",
    imdbRating: "9.2",
    imdbVotes: "1,694,603",
    imdbID: "tt0068646",
    Type: "movie",
    DVD: "01 Aug 2013",
    BoxOffice: "$134,966,411",
    Production: "Paramount Pictures",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Godfather: Part II",
    Year: "1974",
    Rated: "R",
    Released: "18 Dec 1974",
    Runtime: "202 min",
    Genre: "Crime, Drama",
    Director: "Francis Ford Coppola",
    Writer: "Francis Ford Coppola, Mario Puzo",
    Actors: "Al Pacino, Robert De Niro, Robert Duvall",
    Plot: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
    Language: "English, Italian, Spanish, Latin, Sicilian",
    Country: "United States",
    Awards: "Won 6 Oscars. 17 wins & 20 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
      {
        Source: "Metacritic",
        Value: "90/100",
      },
    ],
    Metascore: "90",
    imdbRating: "9.0",
    imdbVotes: "1,177,124",
    imdbID: "tt0071562",
    Type: "movie",
    DVD: "24 May 2005",
    BoxOffice: "$47,834,595",
    Production: "Paramount Pictures, Coppola Company",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Dark Knight",
    Year: "2008",
    Rated: "PG-13",
    Released: "18 Jul 2008",
    Runtime: "152 min",
    Genre: "Action, Crime, Drama",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan, David S. Goyer",
    Actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
    Plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    Language: "English, Mandarin",
    Country: "United States, United Kingdom",
    Awards: "Won 2 Oscars. 159 wins & 163 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
      {
        Source: "Metacritic",
        Value: "84/100",
      },
    ],
    Metascore: "84",
    imdbRating: "9.0",
    imdbVotes: "2,403,192",
    imdbID: "tt0468569",
    Type: "movie",
    DVD: "09 Dec 2008",
    BoxOffice: "$534,858,444",
    Production: "Syncopy",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Schindler's List",
    Year: "1993",
    Rated: "R",
    Released: "04 Feb 1994",
    Runtime: "195 min",
    Genre: "Biography, Drama, History",
    Director: "Steven Spielberg",
    Writer: "Thomas Keneally, Steven Zaillian",
    Actors: "Liam Neeson, Ralph Fiennes, Ben Kingsley",
    Plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
    Language: "English, Hebrew, German, Polish, Latin",
    Country: "United States",
    Awards: "Won 7 Oscars. 91 wins & 49 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.9/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "98%",
      },
      {
        Source: "Metacritic",
        Value: "94/100",
      },
    ],
    Metascore: "94",
    imdbRating: "8.9",
    imdbVotes: "1,259,395",
    imdbID: "tt0108052",
    Type: "movie",
    DVD: "05 Mar 2013",
    BoxOffice: "$96,898,818",
    Production: "Universal Pictures, Amblin Entertainment",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Lord of the Rings: The Return of the King",
    Year: "2003",
    Rated: "PG-13",
    Released: "17 Dec 2003",
    Runtime: "201 min",
    Genre: "Action, Adventure, Drama",
    Director: "Peter Jackson",
    Writer: "J.R.R. Tolkien, Fran Walsh, Philippa Boyens",
    Actors: "Elijah Wood, Viggo Mortensen, Ian McKellen",
    Plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    Language: "English, Quenya, Old English, Sindarin",
    Country: "New Zealand, United States",
    Awards: "Won 11 Oscars. 209 wins & 124 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.9/10",
      },
      {
        Source: "Metacritic",
        Value: "94/100",
      },
    ],
    Metascore: "94",
    imdbRating: "8.9",
    imdbVotes: "1,700,748",
    imdbID: "tt0167260",
    Type: "movie",
    DVD: "25 May 2004",
    BoxOffice: "$377,845,905",
    Production: "New Line Cinema, Saul Zaentz Company",
    Website: "N/A",
    Response: "True",
  },
  {
    Actors: "Brad Pitt, Edward Norton, Meat Loaf",
    Awards: "Nominated for 1 Oscar. 11 wins & 38 nominations total",
    BoxOffice: "$37,030,102",
    Country: "Germany, United States",
    DVD: "14 Oct 2003",
    Director: "David Fincher",
    Genre: "Drama",
    Language: "English",
    Metascore: "66",
    Plot: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Production:
      "Art Linson Productions, Fox 2000 Pictures, Taurus Film, New Regency Pictures",
    Rated: "R",

    Released: "15 Oct 1999",
    Response: "True",
    Runtime: "139 min",
    Title: "Fight Club",
    Type: "movie",
    Website: "N/A",
    Writer: "Chuck Palahniuk, Jim Uhls",
    Year: "1999",
    imdbID: "tt0137523",
    imdbRating: "8.8",
    imdbVotes: "1,920,113",
  },
  {
    Title: "Forrest Gump",
    Year: "1994",
    Rated: "PG-13",
    Released: "06 Jul 1994",
    Runtime: "142 min",
    Genre: "Drama, Romance",
    Director: "Robert Zemeckis",
    Writer: "Winston Groom, Eric Roth",
    Actors: "Tom Hanks, Robin Wright, Gary Sinise",
    Plot: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweeth",
    Language: "English",
    Country: "United States",
    Awards: "Won 6 Oscars. 50 wins & 75 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.8/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "71%",
      },
      {
        Source: "Metacritic",
        Value: "82/100",
      },
    ],
    Metascore: "82",
    imdbRating: "8.8",
    imdbVotes: "1,893,086",
    imdbID: "tt0109830",
    Type: "movie",
    DVD: "01 Aug 2013",
    BoxOffice: "$330,455,270",
    Production: "Paramount Pictures",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Star Wars: Episode V - The Empire Strikes Back",
    Year: "1980",
    Rated: "PG",
    Released: "20 Jun 1980",
    Runtime: "124 min",
    Genre: "Action, Adventure, Fantasy",
    Director: "Irvin Kershner",
    Writer: "Leigh Brackett, Lawrence Kasdan, George Lucas",
    Actors: "Mark Hamill, Harrison Ford, Carrie Fisher",
    Plot: "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.",
    Language: "English",
    Country: "United States, United Kingdom",
    Awards: "Won 2 Oscars. 25 wins & 20 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "94%",
      },
      {
        Source: "Metacritic",
        Value: "82/100",
      },
    ],
    Metascore: "82",
    imdbRating: "8.7",
    imdbVotes: "1,199,138",
    imdbID: "tt0080684",
    Type: "movie",
    DVD: "10 Apr 2015",
    BoxOffice: "$292,753,960",
    Production: "Lucasfilm Ltd.",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Matrix",
    Year: "1999",
    Rated: "R",
    Released: "31 Mar 1999",
    Runtime: "136 min",
    Genre: "Action, Sci-Fi",
    Director: "Lana Wachowski, Lilly Wachowski",
    Writer: "Lilly Wachowski, Lana Wachowski",
    Actors: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    Plot: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    Language: "English",
    Country: "United States, Australia",
    Awards: "Won 4 Oscars. 42 wins & 51 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.7/10",
      },
      {
        Source: "Metacritic",
        Value: "73/100",
      },
    ],
    Metascore: "73",
    imdbRating: "8.7",
    imdbVotes: "1,734,227",
    imdbID: "tt0133093",
    Type: "movie",
    DVD: "15 May 2007",
    BoxOffice: "$171,479,930",
    Production: "Village Roadshow Prod., Silver Pictures",
    Website: "N/A",
    Response: "True",
  },
];
